-- Reset canonical LineItems to match in-code statement catalog.
DELETE FROM "LineItem";
INSERT INTO "LineItem" ("code","label","statementType","parentCode","sortOrder","unit","isInput") VALUES
('BAL_A__TOTAL','Bilanz: Aktiva','BALANCE_ASSET',NULL,1,'EUR',false),
('BAL_A__TOTAL__A','A. Anlagevermögen','BALANCE_ASSET','BAL_A__TOTAL',2,'EUR',true),
('BAL_A__TOTAL__A__A_I','I. Immaterielle Vermögenswerte','BALANCE_ASSET','BAL_A__TOTAL__A',3,'EUR',true),
('BAL_A__TOTAL__A__A_I__A_I_1','1. Selbst geschaffene gewerbliche Schutzrechte und ähnliche Rechte und Werte','BALANCE_ASSET','BAL_A__TOTAL__A__A_I',4,'EUR',true),
('BAL_A__TOTAL__A__A_I__A_I_2','2. Entgeltlich erworbene Konzessionen, gewerbliche Schutzrechte und ähnliche Rechte und Werte','BALANCE_ASSET','BAL_A__TOTAL__A__A_I',5,'EUR',true),
('BAL_A__TOTAL__A__A_I__A_I_3','3. Geschäfts- und Firmenwert','BALANCE_ASSET','BAL_A__TOTAL__A__A_I',6,'EUR',true),
('BAL_A__TOTAL__A__A_I__A_I_4','4. Geleistete Anzahlungen','BALANCE_ASSET','BAL_A__TOTAL__A__A_I',7,'EUR',true),
('BAL_A__TOTAL__A__A_II','II. Sachanlagen','BALANCE_ASSET','BAL_A__TOTAL__A',8,'EUR',true),
('BAL_A__TOTAL__A__A_II__A_II_1','1. Grundstücke, grundstücksgleiche Rechte und Bauten einschließlich der Bauten auf fremden Grundstücken','BALANCE_ASSET','BAL_A__TOTAL__A__A_II',9,'EUR',true),
('BAL_A__TOTAL__A__A_II__A_II_2','2. Technische Anlagen und Maschinen','BALANCE_ASSET','BAL_A__TOTAL__A__A_II',10,'EUR',true),
('BAL_A__TOTAL__A__A_II__A_II_3','3. Andere Anlagen, Betriebs- und Geschäftsausstattung','BALANCE_ASSET','BAL_A__TOTAL__A__A_II',11,'EUR',true),
('BAL_A__TOTAL__A__A_II__A_II_4','4. Geleistete Anzahlungen und Anlagen im Bau','BALANCE_ASSET','BAL_A__TOTAL__A__A_II',12,'EUR',true),
('BAL_A__TOTAL__A__A_III','III. Finanzanlagen','BALANCE_ASSET','BAL_A__TOTAL__A',13,'EUR',true),
('BAL_A__TOTAL__A__A_III__A_III_1','1. Anteile an verbundenen Unternehmen','BALANCE_ASSET','BAL_A__TOTAL__A__A_III',14,'EUR',true),
('BAL_A__TOTAL__A__A_III__A_III_2','2. Ausleihungen an verbundene Unternehmen','BALANCE_ASSET','BAL_A__TOTAL__A__A_III',15,'EUR',true),
('BAL_A__TOTAL__A__A_III__A_III_3','3. Beteiligungen','BALANCE_ASSET','BAL_A__TOTAL__A__A_III',16,'EUR',true),
('BAL_A__TOTAL__A__A_III__A_III_4','4. Ausleihungen an Unternehmen, mit denen ein Beteiligungsverhältnis besteht','BALANCE_ASSET','BAL_A__TOTAL__A__A_III',17,'EUR',true),
('BAL_A__TOTAL__A__A_III__A_III_5','5. Wertpapiere des Anlagevermögens','BALANCE_ASSET','BAL_A__TOTAL__A__A_III',18,'EUR',true),
('BAL_A__TOTAL__A__A_III__A_III_6','6. Sonstige Ausleihungen und Finanzanlagen','BALANCE_ASSET','BAL_A__TOTAL__A__A_III',19,'EUR',true),
('BAL_A__TOTAL__B','B. Umlaufvermögen','BALANCE_ASSET','BAL_A__TOTAL',20,'EUR',true),
('BAL_A__TOTAL__B__B_1','I. Vorräte','BALANCE_ASSET','BAL_A__TOTAL__B',21,'EUR',true),
('BAL_A__TOTAL__B__B_1__B_1_1','1. Roh-, Hilfs- und Betriebsstoffe','BALANCE_ASSET','BAL_A__TOTAL__B__B_1',22,'EUR',true),
('BAL_A__TOTAL__B__B_1__B_1_2','2. Unfertige Erzeugnisse und Leistungen','BALANCE_ASSET','BAL_A__TOTAL__B__B_1',23,'EUR',true),
('BAL_A__TOTAL__B__B_1__B_1_3','3. Fertige Erzeugnisse und Waren','BALANCE_ASSET','BAL_A__TOTAL__B__B_1',24,'EUR',true),
('BAL_A__TOTAL__B__B_1__B_1_4','4. Geleistete Anzahlungen','BALANCE_ASSET','BAL_A__TOTAL__B__B_1',25,'EUR',true),
('BAL_A__TOTAL__B__B_2','II. Forderungen und sonstige Vermögenswerte','BALANCE_ASSET','BAL_A__TOTAL__B',26,'EUR',true),
('BAL_A__TOTAL__B__B_2__B_2_1','1. Forderungen aus Lieferungen und Leistungen','BALANCE_ASSET','BAL_A__TOTAL__B__B_2',27,'EUR',true),
('BAL_A__TOTAL__B__B_2__B_2_2','2. Forderungen gegen verbundene Unternehmen','BALANCE_ASSET','BAL_A__TOTAL__B__B_2',28,'EUR',true),
('BAL_A__TOTAL__B__B_2__B_2_3','3. Forderungen gegen Unternehmen, mit denen ein Beteiligungsverhältnis besteht','BALANCE_ASSET','BAL_A__TOTAL__B__B_2',29,'EUR',true),
('BAL_A__TOTAL__B__B_2__B_2_4','4. Sonstige Vermögenswerte','BALANCE_ASSET','BAL_A__TOTAL__B__B_2',30,'EUR',true),
('BAL_A__TOTAL__B__B_3','III. Wertpapiere','BALANCE_ASSET','BAL_A__TOTAL__B',31,'EUR',true),
('BAL_A__TOTAL__B__B_3__B_3_1','1. Anteile an verbundenen Unternehmen','BALANCE_ASSET','BAL_A__TOTAL__B__B_3',32,'EUR',true),
('BAL_A__TOTAL__B__B_3__B_3_2','2. Sonstige Wertpapiere','BALANCE_ASSET','BAL_A__TOTAL__B__B_3',33,'EUR',true),
('BAL_A__TOTAL__B__B_4','IV. Kassenbestand, Guthaben bei Kreditinstituten','BALANCE_ASSET','BAL_A__TOTAL__B',34,'EUR',true),
('BAL_A__TOTAL__C','C. Rechnungsabgrenzungsposten','BALANCE_ASSET','BAL_A__TOTAL',35,'EUR',true),
('BAL_A__TOTAL__D','D. Aktive latente Steuern','BALANCE_ASSET','BAL_A__TOTAL',36,'EUR',true),
('BAL_A__TOTAL__E','E. Aktiver Unterschiedsbetrag aus der Vermögensverrechnung','BALANCE_ASSET','BAL_A__TOTAL',37,'EUR',true),
('BAL_P__TOTAL','Bilanz: Passiva','BALANCE_LIAB',NULL,1,'EUR',false),
('BAL_P__TOTAL__A','A. Eigenkapital','BALANCE_LIAB','BAL_P__TOTAL',2,'EUR',true),
('BAL_P__TOTAL__A__A_I','I. Gezeichnetes Kapital','BALANCE_LIAB','BAL_P__TOTAL__A',3,'EUR',true),
('BAL_P__TOTAL__A__A_II','II. Kapitalrücklage','BALANCE_LIAB','BAL_P__TOTAL__A',4,'EUR',true),
('BAL_P__TOTAL__A__A_III','III. Gewinnrücklagen','BALANCE_LIAB','BAL_P__TOTAL__A',5,'EUR',true),
('BAL_P__TOTAL__A__A_IV','IV. Gewinnvortrag/Verlustvortrag','BALANCE_LIAB','BAL_P__TOTAL__A',6,'EUR',true),
('BAL_P__TOTAL__A__A_V','V. Jahresüberschuss/Jahresfehlbetrag','BALANCE_LIAB','BAL_P__TOTAL__A',7,'EUR',true),
('BAL_P__TOTAL__B','B. Sonderposten','BALANCE_LIAB','BAL_P__TOTAL',8,'EUR',true),
('BAL_P__TOTAL__C','C. Rückstellungen','BALANCE_LIAB','BAL_P__TOTAL',9,'EUR',true),
('BAL_P__TOTAL__C__C_1','1. Rückstellungen für Pensionen und ähnliche Verpflichtungen','BALANCE_LIAB','BAL_P__TOTAL__C',10,'EUR',true),
('BAL_P__TOTAL__C__C_2','2. Steuerrückstellungen','BALANCE_LIAB','BAL_P__TOTAL__C',11,'EUR',true),
('BAL_P__TOTAL__C__C_3','3. Sonstige Rückstellungen','BALANCE_LIAB','BAL_P__TOTAL__C',12,'EUR',true),
('BAL_P__TOTAL__D','D. Verbindlichkeiten','BALANCE_LIAB','BAL_P__TOTAL',13,'EUR',true),
('BAL_P__TOTAL__D__D_1','1. Anleihen, davon konvertibel','BALANCE_LIAB','BAL_P__TOTAL__D',14,'EUR',true),
('BAL_P__TOTAL__D__D_1__D_1_DAVON','davon mit einer RLZ < 1 Jahr','BALANCE_LIAB','BAL_P__TOTAL__D__D_1',15,'EUR',true),
('BAL_P__TOTAL__D__D_2','2. Verbindlichkeiten gegenüber Kreditinstituten','BALANCE_LIAB','BAL_P__TOTAL__D',16,'EUR',true),
('BAL_P__TOTAL__D__D_2__D_2_DAVON','davon mit einer RLZ < 1 Jahr','BALANCE_LIAB','BAL_P__TOTAL__D__D_2',17,'EUR',true),
('BAL_P__TOTAL__D__D_3','3. Erhaltene Anzahlungen','BALANCE_LIAB','BAL_P__TOTAL__D',18,'EUR',true),
('BAL_P__TOTAL__D__D_3__D_3_DAVON','davon mit einer RLZ < 1 Jahr','BALANCE_LIAB','BAL_P__TOTAL__D__D_3',19,'EUR',true),
('BAL_P__TOTAL__D__D_4','4. Verbindlichkeiten aus Lieferungen und Leistungen','BALANCE_LIAB','BAL_P__TOTAL__D',20,'EUR',true),
('BAL_P__TOTAL__D__D_4__D_4_DAVON','davon mit einer RLZ < 1 Jahr','BALANCE_LIAB','BAL_P__TOTAL__D__D_4',21,'EUR',true),
('BAL_P__TOTAL__D__D_5','5. Verbindlichkeiten aus der Annahme gezogener Wechsel und der Ausstellung eigener Wechsel','BALANCE_LIAB','BAL_P__TOTAL__D',22,'EUR',true),
('BAL_P__TOTAL__D__D_5__D_5_DAVON','davon mit einer RLZ < 1 Jahr','BALANCE_LIAB','BAL_P__TOTAL__D__D_5',23,'EUR',true),
('BAL_P__TOTAL__D__D_6','6. Verbindlichkeiten gegenüber verbundenen Unternehmen','BALANCE_LIAB','BAL_P__TOTAL__D',24,'EUR',true),
('BAL_P__TOTAL__D__D_6__D_6_DAVON','davon mit einer RLZ < 1 Jahr','BALANCE_LIAB','BAL_P__TOTAL__D__D_6',25,'EUR',true),
('BAL_P__TOTAL__D__D_7','7. Verbindlichkeiten gegenüber Gesellschaftern','BALANCE_LIAB','BAL_P__TOTAL__D',26,'EUR',true),
('BAL_P__TOTAL__D__D_7__D_7_DAVON','davon mit einer RLZ < 1 Jahr','BALANCE_LIAB','BAL_P__TOTAL__D__D_7',27,'EUR',true),
('BAL_P__TOTAL__D__D_8','8. Verbindlichkeiten gegenüber Unternehmen, mit denen ein Beteiligungsverhältnis besteht','BALANCE_LIAB','BAL_P__TOTAL__D',28,'EUR',true),
('BAL_P__TOTAL__D__D_8__D_8_DAVON','davon mit einer RLZ < 1 Jahr','BALANCE_LIAB','BAL_P__TOTAL__D__D_8',29,'EUR',true),
('BAL_P__TOTAL__D__D_9','9. Sonstige Verbindlichkeiten','BALANCE_LIAB','BAL_P__TOTAL__D',30,'EUR',true),
('BAL_P__TOTAL__D__D_9__D_9_DAVON','davon mit einer RLZ < 1 Jahr','BALANCE_LIAB','BAL_P__TOTAL__D__D_9',31,'EUR',true),
('BAL_P__TOTAL__E','E. Rechnungsabgrenzungsposten','BALANCE_LIAB','BAL_P__TOTAL',32,'EUR',true),
('BAL_P__TOTAL__F','F. Passive latente Steuern','BALANCE_LIAB','BAL_P__TOTAL',33,'EUR',true),
('UKV__UMSATZ','Umsatzerlöse','INCOME_STATEMENT_UKV',NULL,1,'EUR',true),
('UKV__HKS','Herstellungskosten','INCOME_STATEMENT_UKV',NULL,2,'EUR',true),
('UKV__BRUTTO','Bruttoergebnis','INCOME_STATEMENT_UKV',NULL,3,'EUR',false),
('UKV__SBE','Sonstige betriebliche Erträge','INCOME_STATEMENT_UKV',NULL,4,'EUR',true),
('UKV__ROH','Rohergebnis','INCOME_STATEMENT_UKV',NULL,5,'EUR',false),
('UKV__VVK','Vertriebs- und Verwaltungskosten','INCOME_STATEMENT_UKV',NULL,6,'EUR',true),
('UKV__VVK__VVK_V','davon Vertriebskosten','INCOME_STATEMENT_UKV','UKV__VVK',7,'EUR',true),
('UKV__VVK__VVK_A','davon allgemeine Verwaltungskosten','INCOME_STATEMENT_UKV','UKV__VVK',8,'EUR',true),
('UKV__FEK','Forschungs- und Entwicklungskosten','INCOME_STATEMENT_UKV',NULL,9,'EUR',true),
('UKV__SBA','Sonstige betriebliche Aufwendungen','INCOME_STATEMENT_UKV',NULL,10,'EUR',true),
('UKV__BETR','Betriebsergebnis','INCOME_STATEMENT_UKV',NULL,11,'EUR',false),
('UKV__BETEIL','Beteiligungsergebnis','INCOME_STATEMENT_UKV',NULL,12,'EUR',true),
('UKV__ZINS_E','Zinsen und ähnliche Erträge','INCOME_STATEMENT_UKV',NULL,13,'EUR',true),
('UKV__ZINS_A','Zinsen und ähnliche Aufwendungen','INCOME_STATEMENT_UKV',NULL,14,'EUR',true),
('UKV__UEBR_FIN','Übriges Finanzergebnis','INCOME_STATEMENT_UKV',NULL,15,'EUR',true),
('UKV__FIN','Finanzergebnis','INCOME_STATEMENT_UKV',NULL,16,'EUR',false),
('UKV__STEUERN','Steuern vom Einkommen und Ertrag','INCOME_STATEMENT_UKV',NULL,17,'EUR',true),
('UKV__STEUERN__STEUERN_LAT','davon latente Steuern','INCOME_STATEMENT_UKV','UKV__STEUERN',18,'EUR',true),
('UKV__STEUERN__STEUERN_LAUF','davon laufende Steuern','INCOME_STATEMENT_UKV','UKV__STEUERN',19,'EUR',true),
('UKV__SONST_ST','Sonstige Steuern','INCOME_STATEMENT_UKV',NULL,20,'EUR',true),
('UKV__JUE','Jahresüberschuss/Jahresfehlbetrag','INCOME_STATEMENT_UKV',NULL,21,'EUR',false),
('UKV__MAT','Angaben zum Materialaufwand:','INCOME_STATEMENT_UKV',NULL,22,'EUR',false),
('UKV__MAT__MAT_RHB','davon Aufwendungen für Roh-, Hilfs- und Betriebsstoffe','INCOME_STATEMENT_UKV','UKV__MAT',23,'EUR',true),
('UKV__MAT__MAT_BL','davon Aufwendungen für bezogene Leistungen','INCOME_STATEMENT_UKV','UKV__MAT',24,'EUR',true),
('UKV__PER','Angaben zum Personalaufwand:','INCOME_STATEMENT_UKV',NULL,25,'EUR',false),
('UKV__PER__PER_LG','davon Löhne und Gehälter','INCOME_STATEMENT_UKV','UKV__PER',26,'EUR',true),
('UKV__PER__PER_SA','davon soziale Abgaben und Aufwendungen für Unterstützung','INCOME_STATEMENT_UKV','UKV__PER',27,'EUR',true),
('UKV__ABSCH','Abschreibungen auf Anlagevermögen','INCOME_STATEMENT_UKV',NULL,28,'EUR',true),
('GKV__UMSATZ','Umsatzerlöse','INCOME_STATEMENT_GKV',NULL,1,'EUR',true),
('GKV__BESTAND','Bestandsveränderung fertige und unfertige Erzeugnisse','INCOME_STATEMENT_GKV',NULL,2,'EUR',true),
('GKV__EIGEN','Andere aktivierte Eigenleistungen','INCOME_STATEMENT_GKV',NULL,3,'EUR',true),
('GKV__GESAMT','Gesamtleistung','INCOME_STATEMENT_GKV',NULL,4,'EUR',false),
('GKV__SBE','Sonstige betriebliche Erträge','INCOME_STATEMENT_GKV',NULL,5,'EUR',true),
('GKV__MAT','Materialaufwand','INCOME_STATEMENT_GKV',NULL,6,'EUR',true),
('GKV__MAT__MAT_RHB','Davon Aufwendungen für Roh-, Hilfs- und Betriebsstoffe','INCOME_STATEMENT_GKV','GKV__MAT',7,'EUR',true),
('GKV__MAT__MAT_BL','Davon Aufwendungen für bezogene Leistungen','INCOME_STATEMENT_GKV','GKV__MAT',8,'EUR',true),
('GKV__ROH','Rohergebnis','INCOME_STATEMENT_GKV',NULL,9,'EUR',false),
('GKV__PER','Personalaufwand','INCOME_STATEMENT_GKV',NULL,10,'EUR',true),
('GKV__PER__PER_LG','Davon Löhne und Gehälter','INCOME_STATEMENT_GKV','GKV__PER',11,'EUR',true),
('GKV__PER__PER_SA','Davon soziale Abgaben und Aufwendungen für Unterstützung','INCOME_STATEMENT_GKV','GKV__PER',12,'EUR',true),
('GKV__ABSCH','Abschreibungen','INCOME_STATEMENT_GKV',NULL,13,'EUR',true),
('GKV__SBA','Sonstige betriebliche Aufwendungen','INCOME_STATEMENT_GKV',NULL,14,'EUR',true),
('GKV__BETR','Betriebsergebnis','INCOME_STATEMENT_GKV',NULL,15,'EUR',false),
('GKV__BETEIL','Beteiligungsergebnis','INCOME_STATEMENT_GKV',NULL,16,'EUR',true),
('GKV__ZINS_E','Zinsen und ähnliche Erträge','INCOME_STATEMENT_GKV',NULL,17,'EUR',true),
('GKV__ZINS_A','Zinsen und ähnliche Aufwendungen','INCOME_STATEMENT_GKV',NULL,18,'EUR',true),
('GKV__UEBR_FIN','Übriges Finanzergebnis','INCOME_STATEMENT_GKV',NULL,19,'EUR',true),
('GKV__FIN','Finanzergebnis','INCOME_STATEMENT_GKV',NULL,20,'EUR',false),
('GKV__STEUERN','Steuern vom Einkommen und Ertrag','INCOME_STATEMENT_GKV',NULL,21,'EUR',true),
('GKV__STEUERN__STEUERN_LAT','Davon latente Steuern','INCOME_STATEMENT_GKV','GKV__STEUERN',22,'EUR',true),
('GKV__STEUERN__STEUERN_LAUF','Davon laufende Steuern','INCOME_STATEMENT_GKV','GKV__STEUERN',23,'EUR',true),
('GKV__SONST_ST','Sonstige Steuern','INCOME_STATEMENT_GKV',NULL,24,'EUR',true),
('GKV__JUE','Jahresüberschuss/Jahresfehlbetrag','INCOME_STATEMENT_GKV',NULL,25,'EUR',false),
('OTH__CASHFLOW','Cashflow','CASHFLOW',NULL,1,'EUR',true),
('OTH__LATENT_RATE','zur Berechnung der latenten Steuern verwendeter Steuersatz (Vorschlag: 39%)','CASHFLOW',NULL,2,'PERCENT',true),
('OTH__EMPLOYEES','Anzahl der Mitarbeiter im Jahresdurchschnitt (Vollzeitäquivalente)','CASHFLOW',NULL,3,'COUNT',true);
