FROM node:24.15.0-alpine

WORKDIR /app

RUN apk add --no-cache postgresql16-client

# Install dependencies
COPY package.json package-lock.json* ./
COPY scripts ./scripts
RUN npm ci || npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]
