name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop", "master"]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v6

      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24.15.0
          cache: "npm"
          cache-dependency-path: app/package-lock.json

      - name: Setup npm retry config
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000

      - name: Install deps
        run: npm ci --prefer-offline --no-audit --no-fund

      - name: Lint
        run: npm run lint

      - name: Prettier check
        run: npx --no-install prettier --ignore-path ../.prettierignore --check ..
