FROM node:24.18.0-alpine

WORKDIR /app

RUN apk add --no-cache postgresql18-client

# Install dependencies
COPY package.json package-lock.json* ./
COPY scripts ./scripts
RUN npm ci || npm install

EXPOSE 3000

CMD ["npm", "run", "dev"]
